/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminLoginRouteRouteImport } from './routes/admin-login/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as NonVendorRouteRouteImport } from './routes/_non-vendor/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminLoginIndexRouteImport } from './routes/admin-login/index'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as NonVendorCompanyRouteImport } from './routes/_non-vendor/company'
import { Route as AdminNonVendorRequestsRouteRouteImport } from './routes/admin/non-vendor-requests/route'
import { Route as NonVendorSettlementsRouteRouteImport } from './routes/_non-vendor/settlements/route'
import { Route as NonVendorInvoicesRouteRouteImport } from './routes/_non-vendor/invoices/route'
import { Route as AdminNonVendorRequestsIndexRouteImport } from './routes/admin/non-vendor-requests/index'
import { Route as NonVendorSettlementsIndexRouteImport } from './routes/_non-vendor/settlements/index'
import { Route as NonVendorInvoicesIndexRouteImport } from './routes/_non-vendor/invoices/index'
import { Route as NonVendorInvoicesNewRouteImport } from './routes/_non-vendor/invoices/new'
import { Route as AdminNonVendorRequestsIdDetailRouteImport } from './routes/admin/non-vendor-requests/$id.detail'
import { Route as NonVendorSettlementsIdProcessRouteImport } from './routes/_non-vendor/settlements/$id.process'
import { Route as NonVendorSettlementsIdDetailRouteImport } from './routes/_non-vendor/settlements/$id.detail'
import { Route as NonVendorInvoicesIdDetailRouteImport } from './routes/_non-vendor/invoices/$id.detail'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRouteRoute = AdminLoginRouteRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const NonVendorRouteRoute = NonVendorRouteRouteImport.update({
  id: '/_non-vendor',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginIndexRoute = AdminLoginIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminLoginRouteRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRouteRoute,
} as any)
const NonVendorCompanyRoute = NonVendorCompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => NonVendorRouteRoute,
} as any)
const AdminNonVendorRequestsRouteRoute =
  AdminNonVendorRequestsRouteRouteImport.update({
    id: '/non-vendor-requests',
    path: '/non-vendor-requests',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const NonVendorSettlementsRouteRoute =
  NonVendorSettlementsRouteRouteImport.update({
    id: '/settlements',
    path: '/settlements',
    getParentRoute: () => NonVendorRouteRoute,
  } as any)
const NonVendorInvoicesRouteRoute = NonVendorInvoicesRouteRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => NonVendorRouteRoute,
} as any)
const AdminNonVendorRequestsIndexRoute =
  AdminNonVendorRequestsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminNonVendorRequestsRouteRoute,
  } as any)
const NonVendorSettlementsIndexRoute =
  NonVendorSettlementsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => NonVendorSettlementsRouteRoute,
  } as any)
const NonVendorInvoicesIndexRoute = NonVendorInvoicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NonVendorInvoicesRouteRoute,
} as any)
const NonVendorInvoicesNewRoute = NonVendorInvoicesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => NonVendorInvoicesRouteRoute,
} as any)
const AdminNonVendorRequestsIdDetailRoute =
  AdminNonVendorRequestsIdDetailRouteImport.update({
    id: '/$id/detail',
    path: '/$id/detail',
    getParentRoute: () => AdminNonVendorRequestsRouteRoute,
  } as any)
const NonVendorSettlementsIdProcessRoute =
  NonVendorSettlementsIdProcessRouteImport.update({
    id: '/$id/process',
    path: '/$id/process',
    getParentRoute: () => NonVendorSettlementsRouteRoute,
  } as any)
const NonVendorSettlementsIdDetailRoute =
  NonVendorSettlementsIdDetailRouteImport.update({
    id: '/$id/detail',
    path: '/$id/detail',
    getParentRoute: () => NonVendorSettlementsRouteRoute,
  } as any)
const NonVendorInvoicesIdDetailRoute =
  NonVendorInvoicesIdDetailRouteImport.update({
    id: '/$id/detail',
    path: '/$id/detail',
    getParentRoute: () => NonVendorInvoicesRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/admin-login': typeof AdminLoginRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/sign-up': typeof SignUpRoute
  '/invoices': typeof NonVendorInvoicesRouteRouteWithChildren
  '/settlements': typeof NonVendorSettlementsRouteRouteWithChildren
  '/admin/non-vendor-requests': typeof AdminNonVendorRequestsRouteRouteWithChildren
  '/company': typeof NonVendorCompanyRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin-login/': typeof AdminLoginIndexRoute
  '/invoices/new': typeof NonVendorInvoicesNewRoute
  '/invoices/': typeof NonVendorInvoicesIndexRoute
  '/settlements/': typeof NonVendorSettlementsIndexRoute
  '/admin/non-vendor-requests/': typeof AdminNonVendorRequestsIndexRoute
  '/invoices/$id/detail': typeof NonVendorInvoicesIdDetailRoute
  '/settlements/$id/detail': typeof NonVendorSettlementsIdDetailRoute
  '/settlements/$id/process': typeof NonVendorSettlementsIdProcessRoute
  '/admin/non-vendor-requests/$id/detail': typeof AdminNonVendorRequestsIdDetailRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/sign-up': typeof SignUpRoute
  '/company': typeof NonVendorCompanyRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin-login': typeof AdminLoginIndexRoute
  '/invoices/new': typeof NonVendorInvoicesNewRoute
  '/invoices': typeof NonVendorInvoicesIndexRoute
  '/settlements': typeof NonVendorSettlementsIndexRoute
  '/admin/non-vendor-requests': typeof AdminNonVendorRequestsIndexRoute
  '/invoices/$id/detail': typeof NonVendorInvoicesIdDetailRoute
  '/settlements/$id/detail': typeof NonVendorSettlementsIdDetailRoute
  '/settlements/$id/process': typeof NonVendorSettlementsIdProcessRoute
  '/admin/non-vendor-requests/$id/detail': typeof AdminNonVendorRequestsIdDetailRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_non-vendor': typeof NonVendorRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/admin-login': typeof AdminLoginRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/sign-up': typeof SignUpRoute
  '/_non-vendor/invoices': typeof NonVendorInvoicesRouteRouteWithChildren
  '/_non-vendor/settlements': typeof NonVendorSettlementsRouteRouteWithChildren
  '/admin/non-vendor-requests': typeof AdminNonVendorRequestsRouteRouteWithChildren
  '/_non-vendor/company': typeof NonVendorCompanyRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin-login/': typeof AdminLoginIndexRoute
  '/_non-vendor/invoices/new': typeof NonVendorInvoicesNewRoute
  '/_non-vendor/invoices/': typeof NonVendorInvoicesIndexRoute
  '/_non-vendor/settlements/': typeof NonVendorSettlementsIndexRoute
  '/admin/non-vendor-requests/': typeof AdminNonVendorRequestsIndexRoute
  '/_non-vendor/invoices/$id/detail': typeof NonVendorInvoicesIdDetailRoute
  '/_non-vendor/settlements/$id/detail': typeof NonVendorSettlementsIdDetailRoute
  '/_non-vendor/settlements/$id/process': typeof NonVendorSettlementsIdProcessRoute
  '/admin/non-vendor-requests/$id/detail': typeof AdminNonVendorRequestsIdDetailRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-login'
    | '/login'
    | '/sign-up'
    | '/invoices'
    | '/settlements'
    | '/admin/non-vendor-requests'
    | '/company'
    | '/admin/dashboard'
    | '/admin/users'
    | '/admin-login/'
    | '/invoices/new'
    | '/invoices/'
    | '/settlements/'
    | '/admin/non-vendor-requests/'
    | '/invoices/$id/detail'
    | '/settlements/$id/detail'
    | '/settlements/$id/process'
    | '/admin/non-vendor-requests/$id/detail'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/sign-up'
    | '/company'
    | '/admin/dashboard'
    | '/admin/users'
    | '/admin-login'
    | '/invoices/new'
    | '/invoices'
    | '/settlements'
    | '/admin/non-vendor-requests'
    | '/invoices/$id/detail'
    | '/settlements/$id/detail'
    | '/settlements/$id/process'
    | '/admin/non-vendor-requests/$id/detail'
  id:
    | '__root__'
    | '/'
    | '/_non-vendor'
    | '/admin'
    | '/admin-login'
    | '/login'
    | '/sign-up'
    | '/_non-vendor/invoices'
    | '/_non-vendor/settlements'
    | '/admin/non-vendor-requests'
    | '/_non-vendor/company'
    | '/admin/dashboard'
    | '/admin/users'
    | '/admin-login/'
    | '/_non-vendor/invoices/new'
    | '/_non-vendor/invoices/'
    | '/_non-vendor/settlements/'
    | '/admin/non-vendor-requests/'
    | '/_non-vendor/invoices/$id/detail'
    | '/_non-vendor/settlements/$id/detail'
    | '/_non-vendor/settlements/$id/process'
    | '/admin/non-vendor-requests/$id/detail'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NonVendorRouteRoute: typeof NonVendorRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AdminLoginRouteRoute: typeof AdminLoginRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignUpRoute: typeof SignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_non-vendor': {
      id: '/_non-vendor'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof NonVendorRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login/': {
      id: '/admin-login/'
      path: '/'
      fullPath: '/admin-login/'
      preLoaderRoute: typeof AdminLoginIndexRouteImport
      parentRoute: typeof AdminLoginRouteRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_non-vendor/company': {
      id: '/_non-vendor/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof NonVendorCompanyRouteImport
      parentRoute: typeof NonVendorRouteRoute
    }
    '/admin/non-vendor-requests': {
      id: '/admin/non-vendor-requests'
      path: '/non-vendor-requests'
      fullPath: '/admin/non-vendor-requests'
      preLoaderRoute: typeof AdminNonVendorRequestsRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_non-vendor/settlements': {
      id: '/_non-vendor/settlements'
      path: '/settlements'
      fullPath: '/settlements'
      preLoaderRoute: typeof NonVendorSettlementsRouteRouteImport
      parentRoute: typeof NonVendorRouteRoute
    }
    '/_non-vendor/invoices': {
      id: '/_non-vendor/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof NonVendorInvoicesRouteRouteImport
      parentRoute: typeof NonVendorRouteRoute
    }
    '/admin/non-vendor-requests/': {
      id: '/admin/non-vendor-requests/'
      path: '/'
      fullPath: '/admin/non-vendor-requests/'
      preLoaderRoute: typeof AdminNonVendorRequestsIndexRouteImport
      parentRoute: typeof AdminNonVendorRequestsRouteRoute
    }
    '/_non-vendor/settlements/': {
      id: '/_non-vendor/settlements/'
      path: '/'
      fullPath: '/settlements/'
      preLoaderRoute: typeof NonVendorSettlementsIndexRouteImport
      parentRoute: typeof NonVendorSettlementsRouteRoute
    }
    '/_non-vendor/invoices/': {
      id: '/_non-vendor/invoices/'
      path: '/'
      fullPath: '/invoices/'
      preLoaderRoute: typeof NonVendorInvoicesIndexRouteImport
      parentRoute: typeof NonVendorInvoicesRouteRoute
    }
    '/_non-vendor/invoices/new': {
      id: '/_non-vendor/invoices/new'
      path: '/new'
      fullPath: '/invoices/new'
      preLoaderRoute: typeof NonVendorInvoicesNewRouteImport
      parentRoute: typeof NonVendorInvoicesRouteRoute
    }
    '/admin/non-vendor-requests/$id/detail': {
      id: '/admin/non-vendor-requests/$id/detail'
      path: '/$id/detail'
      fullPath: '/admin/non-vendor-requests/$id/detail'
      preLoaderRoute: typeof AdminNonVendorRequestsIdDetailRouteImport
      parentRoute: typeof AdminNonVendorRequestsRouteRoute
    }
    '/_non-vendor/settlements/$id/process': {
      id: '/_non-vendor/settlements/$id/process'
      path: '/$id/process'
      fullPath: '/settlements/$id/process'
      preLoaderRoute: typeof NonVendorSettlementsIdProcessRouteImport
      parentRoute: typeof NonVendorSettlementsRouteRoute
    }
    '/_non-vendor/settlements/$id/detail': {
      id: '/_non-vendor/settlements/$id/detail'
      path: '/$id/detail'
      fullPath: '/settlements/$id/detail'
      preLoaderRoute: typeof NonVendorSettlementsIdDetailRouteImport
      parentRoute: typeof NonVendorSettlementsRouteRoute
    }
    '/_non-vendor/invoices/$id/detail': {
      id: '/_non-vendor/invoices/$id/detail'
      path: '/$id/detail'
      fullPath: '/invoices/$id/detail'
      preLoaderRoute: typeof NonVendorInvoicesIdDetailRouteImport
      parentRoute: typeof NonVendorInvoicesRouteRoute
    }
  }
}

interface NonVendorInvoicesRouteRouteChildren {
  NonVendorInvoicesNewRoute: typeof NonVendorInvoicesNewRoute
  NonVendorInvoicesIndexRoute: typeof NonVendorInvoicesIndexRoute
  NonVendorInvoicesIdDetailRoute: typeof NonVendorInvoicesIdDetailRoute
}

const NonVendorInvoicesRouteRouteChildren: NonVendorInvoicesRouteRouteChildren =
  {
    NonVendorInvoicesNewRoute: NonVendorInvoicesNewRoute,
    NonVendorInvoicesIndexRoute: NonVendorInvoicesIndexRoute,
    NonVendorInvoicesIdDetailRoute: NonVendorInvoicesIdDetailRoute,
  }

const NonVendorInvoicesRouteRouteWithChildren =
  NonVendorInvoicesRouteRoute._addFileChildren(
    NonVendorInvoicesRouteRouteChildren,
  )

interface NonVendorSettlementsRouteRouteChildren {
  NonVendorSettlementsIndexRoute: typeof NonVendorSettlementsIndexRoute
  NonVendorSettlementsIdDetailRoute: typeof NonVendorSettlementsIdDetailRoute
  NonVendorSettlementsIdProcessRoute: typeof NonVendorSettlementsIdProcessRoute
}

const NonVendorSettlementsRouteRouteChildren: NonVendorSettlementsRouteRouteChildren =
  {
    NonVendorSettlementsIndexRoute: NonVendorSettlementsIndexRoute,
    NonVendorSettlementsIdDetailRoute: NonVendorSettlementsIdDetailRoute,
    NonVendorSettlementsIdProcessRoute: NonVendorSettlementsIdProcessRoute,
  }

const NonVendorSettlementsRouteRouteWithChildren =
  NonVendorSettlementsRouteRoute._addFileChildren(
    NonVendorSettlementsRouteRouteChildren,
  )

interface NonVendorRouteRouteChildren {
  NonVendorInvoicesRouteRoute: typeof NonVendorInvoicesRouteRouteWithChildren
  NonVendorSettlementsRouteRoute: typeof NonVendorSettlementsRouteRouteWithChildren
  NonVendorCompanyRoute: typeof NonVendorCompanyRoute
}

const NonVendorRouteRouteChildren: NonVendorRouteRouteChildren = {
  NonVendorInvoicesRouteRoute: NonVendorInvoicesRouteRouteWithChildren,
  NonVendorSettlementsRouteRoute: NonVendorSettlementsRouteRouteWithChildren,
  NonVendorCompanyRoute: NonVendorCompanyRoute,
}

const NonVendorRouteRouteWithChildren = NonVendorRouteRoute._addFileChildren(
  NonVendorRouteRouteChildren,
)

interface AdminNonVendorRequestsRouteRouteChildren {
  AdminNonVendorRequestsIndexRoute: typeof AdminNonVendorRequestsIndexRoute
  AdminNonVendorRequestsIdDetailRoute: typeof AdminNonVendorRequestsIdDetailRoute
}

const AdminNonVendorRequestsRouteRouteChildren: AdminNonVendorRequestsRouteRouteChildren =
  {
    AdminNonVendorRequestsIndexRoute: AdminNonVendorRequestsIndexRoute,
    AdminNonVendorRequestsIdDetailRoute: AdminNonVendorRequestsIdDetailRoute,
  }

const AdminNonVendorRequestsRouteRouteWithChildren =
  AdminNonVendorRequestsRouteRoute._addFileChildren(
    AdminNonVendorRequestsRouteRouteChildren,
  )

interface AdminRouteRouteChildren {
  AdminNonVendorRequestsRouteRoute: typeof AdminNonVendorRequestsRouteRouteWithChildren
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminUsersRoute: typeof AdminUsersRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminNonVendorRequestsRouteRoute:
    AdminNonVendorRequestsRouteRouteWithChildren,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminUsersRoute: AdminUsersRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AdminLoginRouteRouteChildren {
  AdminLoginIndexRoute: typeof AdminLoginIndexRoute
}

const AdminLoginRouteRouteChildren: AdminLoginRouteRouteChildren = {
  AdminLoginIndexRoute: AdminLoginIndexRoute,
}

const AdminLoginRouteRouteWithChildren = AdminLoginRouteRoute._addFileChildren(
  AdminLoginRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NonVendorRouteRoute: NonVendorRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AdminLoginRouteRoute: AdminLoginRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  SignUpRoute: SignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
